//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x404040
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x4011b6 - 0x40127f
int main(int argc, char ** argv) {
    int64_t v1 = __readfsqword(40); // 0x4011c5
    puts("Please input your password: ");
    int64_t str; // bp-152, 0x4011b6
    fgets((char *)&str, 128, g1);
    int32_t ini_seg_bytes = strcspn((char *)&str, "\n"); // 0x401212
    int64_t v2; // bp-8, 0x4011b6
    *(char *)((int64_t)&v2 - 144 + (int64_t)ini_seg_bytes) = 0;
    if (atoi((char *)&str) != 2 * *(int32_t *)0x404038) {
        // 0x401255
        puts("Wrong password.");
    } else {
        // 0x401244
        puts("Authentication successful!");
    }
    int64_t result = 0; // 0x401276
    if (v1 != __readfsqword(40)) {
        // 0x401278
        __stack_chk_fail();
        result = &g2;
    }
    // 0x40127d
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (13.3.0)
// Detected functions: 1

