//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t set_password(void);

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x404040
char * g2; // 0x404060
int64_t g3 = 0; // 0x404061
int64_t g4 = 0; // 0x404062
int64_t g5 = 0; // 0x404063
int64_t g6 = 0; // 0x404064
int64_t g7 = 0; // 0x404065
int64_t g8 = 0; // 0x404066
int64_t g9 = 0; // 0x404067
int64_t g10 = 0; // 0x404068
int64_t g11 = 0; // 0x404069
int64_t g12 = 0; // 0x40406a
int64_t g13 = 0; // 0x40406b
int32_t g14;

// ------- Dynamically Linked Functions Without Header --------

void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x4011d6 - 0x401235
int64_t set_password(void) {
    // 0x4011d6
    *(char *)&g2 = 112;
    *(char *)&g3 = 101;
    *(char *)&g4 = 110;
    *(char *)&g5 = 101;
    *(char *)&g6 = 116;
    *(char *)&g7 = 114;
    *(char *)&g8 = 97;
    *(char *)&g9 = 116;
    *(char *)&g10 = 105;
    *(char *)&g11 = 111;
    *(char *)&g12 = 110;
    *(char *)&g13 = 0;
    int64_t result; // 0x4011d6
    return result;
}

// Address range: 0x401235 - 0x40130f
int main(int argc, char ** argv) {
    int64_t v1 = __readfsqword(40); // 0x401244
    set_password();
    puts("Please input your password: ");
    int64_t str; // bp-152, 0x401235
    fgets((char *)&str, 128, g1);
    int32_t ini_seg_bytes = strcspn((char *)&str, "\n"); // 0x40129b
    int64_t v2; // bp-8, 0x401235
    *(char *)((int64_t)&v2 - 144 + (int64_t)ini_seg_bytes) = 0;
    if (strcmp((char *)&str, (char *)&g2) != 0) {
        // 0x4012d6
        printf("Wrong password.\n");
    } else {
        // 0x4012c5
        puts("Authentication successful!");
    }
    int64_t result = 0; // 0x401306
    if (v1 != __readfsqword(40)) {
        // 0x401308
        __stack_chk_fail();
        result = &g14;
    }
    // 0x40130d
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (13.3.0)
// Detected functions: 2

