//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t check_password(int64_t a1);

// --------------------- Global Variables ---------------------

struct _IO_FILE * g1 = NULL; // 0x404040
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x4011b6 - 0x4011da
int64_t check_password(int64_t a1) {
    // 0x4011b6
    return *(int32_t *)0x404038 == (int32_t)a1;
}

// Address range: 0x4011da - 0x4012a4
int main(int argc, char ** argv) {
    int64_t v1 = __readfsqword(40); // 0x4011e9
    puts("Please input your password: ");
    int64_t str; // bp-152, 0x4011da
    fgets((char *)&str, 128, g1);
    int32_t ini_seg_bytes = strcspn((char *)&str, "\n"); // 0x401236
    int64_t v2; // bp-8, 0x4011da
    *(char *)((int64_t)&v2 - 144 + (int64_t)ini_seg_bytes) = 0;
    uint32_t str_as_i = atoi((char *)&str); // 0x40124d
    if ((int32_t)check_password((int64_t)str_as_i) == 0) {
        // 0x40127a
        puts("Wrong password.");
    } else {
        // 0x401269
        puts("Authentication successful!");
    }
    int64_t result = 0; // 0x40129b
    if (v1 != __readfsqword(40)) {
        // 0x40129d
        __stack_chk_fail();
        result = &g2;
    }
    // 0x4012a2
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (13.3.0)
// Detected functions: 2

