//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------------ Structures ------------------------

struct _IO_FILE {
    int32_t e0;
};

// ------------------- Function Prototypes --------------------

int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t function_401000(void);
int32_t function_401080(char * s);
void function_401090(void);
int32_t function_4010a0(char * s, char * reject);
char * function_4010b0(char * s, int32_t n, struct _IO_FILE * stream);
int32_t function_4010c0(char * nptr);
int64_t function_401100(void);
int64_t function_401110(void);
int64_t function_401140(void);
int64_t function_401180(void);
int64_t function_4011b0(void);
int64_t function_4011b6(void);
int64_t function_401280(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x403fe0
struct _IO_FILE * g2 = NULL; // 0x404040
char g3 = 0; // 0x404048
int32_t g4;

// ------- Dynamically Linked Functions Without Header --------

void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x401000 - 0x40101b
int64_t function_401000(void) {
    int64_t result = 0; // 0x401012
    if (g1 != 0) {
        // 0x401014
        __gmon_start__();
        result = &g4;
    }
    // 0x401016
    return result;
}

// Address range: 0x401080 - 0x40108a
int32_t function_401080(char * s) {
    // 0x401080
    return puts(s);
}

// Address range: 0x401090 - 0x40109a
void function_401090(void) {
    // 0x401090
    __stack_chk_fail();
}

// Address range: 0x4010a0 - 0x4010aa
int32_t function_4010a0(char * s, char * reject) {
    // 0x4010a0
    return strcspn(s, reject);
}

// Address range: 0x4010b0 - 0x4010ba
char * function_4010b0(char * s, int32_t n, struct _IO_FILE * stream) {
    // 0x4010b0
    return fgets(s, n, stream);
}

// Address range: 0x4010c0 - 0x4010ca
int32_t function_4010c0(char * nptr) {
    // 0x4010c0
    return atoi(nptr);
}

// Address range: 0x4010d0 - 0x4010f6
int64_t entry_point(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x4010d0
    int64_t v1; // 0x4010d0
    __libc_start_main(0x4011b6, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x401100 - 0x401105
int64_t function_401100(void) {
    // 0x401100
    int64_t result; // 0x401100
    return result;
}

// Address range: 0x401110 - 0x401131
int64_t function_401110(void) {
    // 0x401110
    return (int64_t)&g2;
}

// Address range: 0x401140 - 0x401171
int64_t function_401140(void) {
    // 0x401140
    return 0;
}

// Address range: 0x401180 - 0x4011a1
int64_t function_401180(void) {
    // 0x401180
    if (g3 != 0) {
        // 0x4011a0
        int64_t result; // 0x401180
        return result;
    }
    int64_t result2 = function_401110(); // 0x401191
    g3 = 1;
    return result2;
}

// Address range: 0x4011b0 - 0x4011b6
int64_t function_4011b0(void) {
    // 0x4011b0
    return function_401140();
}

// Address range: 0x4011b6 - 0x40127d
int64_t function_4011b6(void) {
    int64_t v1 = __readfsqword(40); // 0x4011c5
    puts("Please input your password: ");
    int64_t str; // bp-152, 0x4011b6
    fgets((char *)&str, 128, g2);
    int32_t ini_seg_bytes = strcspn((char *)&str, "\n"); // 0x401212
    int64_t v2; // bp-8, 0x4011b6
    *(char *)((int64_t)&v2 - 144 + (int64_t)ini_seg_bytes) = 0;
    if (atoi((char *)&str) != *(int32_t *)0x404038) {
        // 0x401253
        puts("Wrong password.");
    } else {
        // 0x401242
        puts("Authentication successful!");
    }
    int64_t result = 0; // 0x401274
    if (v1 != __readfsqword(40)) {
        // 0x401276
        __stack_chk_fail();
        result = &g4;
    }
    // 0x40127b
    return result;
}

// Address range: 0x401280 - 0x40128d
int64_t function_401280(void) {
    // 0x401280
    int64_t result; // 0x401280
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (13.3.0)
// Detected functions: 14

